name: Prod

on: push

jobs:
  Prod:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Setting up the environment...
        uses: actions/checkout@v2

      - name: 📦 Setting up TypeScript and pm2...

        run: npm i -g typescript pm2

      - name: 🔧 Building the package...

        run: npm run build

      - name: 👀 Setting the pm2...

        run: npm run pm2
